# Generated by Django 5.2.12 on 2026-03-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Allows the cook to manually toggle their visibility to customers.'),
        ),
    ]
