# Generated by Django 5.2.12 on 2026-04-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cookprofile_is_available'),
        ('meals', '0004_remove_pickup_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickupLocation',
        ),
    ]
