# Generated by Django 5.2.12 on 2026-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pickup_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookprofile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
