# Generated by Django 5.2.12 on 2026-03-30 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('delivery', '0001_initial'),
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('fulfillment_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10)),
                ('pickup_code', models.CharField(blank=True, max_length=6)),
                ('pickup_time_actual', models.DateTimeField(blank=True, null=True)),
                ('delivery_address_street', models.CharField(blank=True, max_length=255)),
                ('delivery_address_city', models.CharField(blank=True, max_length=100)),
                ('delivery_address_state', models.CharField(blank=True, max_length=100)),
                ('delivery_address_zip', models.CharField(blank=True, max_length=20)),
                ('delivery_address_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_address_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('delivery_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('failed_delivery', 'Failed Delivery')], max_length=20, null=True)),
                ('rider_name', models.CharField(blank=True, max_length=255)),
                ('rider_phone', models.CharField(blank=True, max_length=20)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('special_instructions', models.TextField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('acceptance_deadline', models.DateTimeField(blank=True, help_text='Cook must accept before this time', null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('cook', 'Cook'), ('system', 'System')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.cookprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryslot')),
                ('pickup_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='meals.pickupslot')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
