# Generated by Django 5.2.12 on 2026-04-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of selected extras: [{"id": "...", "name": "...", "price": "1.50", "quantity": 2}]'),
        ),
    ]
