# Generated by Django 5.2.12 on 2026-03-30 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_orders', models.IntegerField(default=5)),
                ('booked_orders', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='accounts.cookprofile')),
            ],
            options={
                'db_table': 'delivery_slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_type', models.CharField(choices=[('radius', 'Radius'), ('polygon', 'Polygon')], default='radius', max_length=10)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('polygon_coords', models.JSONField(blank=True, default=list)),
                ('delivery_fee_type', models.CharField(choices=[('flat', 'Flat'), ('per_km', 'Per KM'), ('free', 'Free')], default='flat', max_length=10)),
                ('delivery_fee_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estimated_delivery_mins', models.IntegerField(default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='accounts.cookprofile')),
            ],
            options={
                'db_table': 'delivery_zones',
            },
        ),
    ]
