# Generated by Django 5.2.12 on 2026-03-15 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('short_description', models.CharField(blank=True, max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR')], default='INR', max_length=3)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('meal_kit', 'Meal Kit')], max_length=10)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('meal_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('egg', 'Egg')], max_length=7)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('allergen_info', models.JSONField(blank=True, default=list)),
                ('spice_level', models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('spicy', 'Spicy'), ('extra_spicy', 'Extra Spicy')], default='medium', max_length=12)),
                ('serving_size', models.CharField(blank=True, max_length=100)),
                ('calories_approx', models.IntegerField(blank=True, null=True)),
                ('preparation_time_mins', models.IntegerField(default=30)),
                ('fulfillment_modes', models.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('available_days', models.JSONField(default=list)),
                ('total_orders', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.cookprofile')),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meals.meal')),
            ],
            options={
                'db_table': 'meal_images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_orders', models.IntegerField(default=10)),
                ('booked_orders', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('location_label', models.CharField(blank=True, max_length=100)),
                ('location_street', models.CharField(blank=True, max_length=255)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_slots', to='accounts.cookprofile')),
            ],
            options={
                'db_table': 'pickup_slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='RecurringSlotTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_of_week', models.JSONField(default=list)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_orders', models.IntegerField(default=10)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slot_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='accounts.cookprofile')),
            ],
            options={
                'db_table': 'recurring_slot_templates',
            },
        ),
    ]
