# Generated by Django 5.2.12 on 2026-03-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealextra',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD'), ('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR')], default='AUD', max_length=3),
        ),
        migrations.AddField(
            model_name='mealextra',
            name='item_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('egg', 'Egg')], default='veg', max_length=7),
        ),
    ]
