# Generated by Django 5.2.12 on 2026-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cookprofile_is_available'),
        ('meals', '0002_mealextra_currency_mealextra_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='pickup_locations',
            field=models.ManyToManyField(blank=True, related_name='meals', to='accounts.pickuplocation'),
        ),
    ]
