# Generated by Django 5.2.12 on 2026-04-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_remove_pickup_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='short_description',
        ),
    ]
