# Generated by Django 5.2.12 on 2026-04-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
