# Generated by Django 5.2.12 on 2026-03-15 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat_amount', 'Flat Amount')], max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('applies_to_delivery_fee', models.BooleanField(default=False)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('usage_limit_total', models.IntegerField(default=100)),
                ('usage_limit_per_user', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('applicable_to', models.CharField(choices=[('all', 'All'), ('specific_cooks', 'Specific Cooks'), ('specific_meals', 'Specific Meals'), ('new_users', 'New Users')], default='all', max_length=20)),
                ('applicable_fulfillment', models.CharField(choices=[('all', 'All'), ('pickup_only', 'Pickup Only'), ('delivery_only', 'Delivery Only')], default='all', max_length=15)),
                ('applicable_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('admin', 'Admin'), ('cook', 'Cook')], default='admin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_usages',
            },
        ),
    ]
